# CodeRabbit AI Review Configuration
# Project Chimera - AI Code Review Policy

language: en
early_access: false

reviews:
  profile: "chill"
  high_level_summary: true
  auto_title_placeholder: ""
  collapse_walkthrough: false
